name: Build Kernel A23 - FIXED PATH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Kernel Source
        uses: actions/checkout@v4

      - name: Add KernelSU
        run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          
      - name: Install Compilers
        run: |
          sudo apt update
          sudo apt install -y clang-15 llvm-15 lld-15 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
          
      - name: Build Kernel
        run: |
          # Definindo as variáveis diretamente no comando para não haver erro de "Target not found"
          make O=out rsuntk_defconfig ARCH=arm64
          
          # Fix vDSO
          sed -i 's/KBUILD_CFLAGS += $(arm64_relocate_vdso_flags)/KBUILD_CFLAGS += $(arm64_relocate_vdso_flags) -fPIC -fno-stack-protector/g' arch/arm64/kernel/vdso/Makefile
          
          # Desativa travas
          scripts/config --file out/.config --disable MODULE_SIG --disable SYSTEM_TRUSTED_KEYRING --disable PANIC_ON_OOPS
          
          make O=out olddefconfig ARCH=arm64
          
          # COMANDO DE COMPILAÇÃO CORRIGIDO
          make -j$(nproc --all) O=out \
          ARCH=arm64 \
          CC=clang-15 \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          LD=ld.lld-15 \
          LLVM_IAS=0 \
          Image

      - name: Check and Move Image
        run: |
          # Verifica se o arquivo existe antes de tentar o upload
          if [ -f out/arch/arm64/boot/Image ]; then
            echo "Kernel gerado com sucesso!"
            cp out/arch/arm64/boot/Image ./Image-A23
          else
            echo "ERRO: O arquivo Image não foi encontrado em out/arch/arm64/boot/"
            exit 1
          fi

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_A23_Final
          path: ./Image-A23
