name: A23_Variant_H_Fragmenter
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: potatogeek/kernel-a235m-f
          ref: main
          path: kernel_source

      - name: Setup Environment
        run: |
          sudo apt update -y
          sudo apt install bc cpio flex bison git gcc g++ tar perl curl libc++-dev lz4 libssl-dev python2 -y
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          mkdir toolchains && cd toolchains
          git clone --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b1.git clang
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 google

      - name: Create Config Fragment
        run: |
          cd kernel_source
          # Cria um ficheiro com as configs de performance
          echo "CONFIG_LTO_CLANG_FULL=y" > android16.config
          echo "CONFIG_OVERLAY_FS=y" >> android16.config
          echo "CONFIG_BPF_SYSCALL=y" >> android16.config
          echo "CONFIG_KSU=y" >> android16.config
          echo "CONFIG_KSU_SUSFS=y" >> android16.config
          echo "# CONFIG_SHADOW_CALL_STACK is not set" >> android16.config
          
          # Funde as configurações
          ARCH=arm64 scripts/kconfig/merge_config.sh -m arch/arm64/configs/vendor/a23_eur_open_defconfig android16.config

      - name: Audio Physical Fix & Build
        run: |
          export PATH=$(pwd)/toolchains/clang/bin:$(pwd)/toolchains/google/bin:$PATH
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-
          cd kernel_source
          
          # Cópia física para garantir o techpack
          ADR="techpack/audio/asoc/codecs/tas256x"
          mkdir -p $ADR/os_layer/src/physical_layer/inc
          cp $ADR/physical_layer/inc/*.h $ADR/os_layer/src/physical_layer/inc/ 2>/dev/null || true
          
          make olddefconfig
          make -j$(nproc --all) CC=clang CROSS_COMPILE=aarch64-linux-android- LLVM=1 KCFLAGS="-O3 -w"

      - name: Create VBMeta
        run: |
          wget https://raw.githubusercontent.com/external-avb/avb/master/avbtool.py
          python3 avbtool.py make_vbmeta_image --flags 2 --padding_size 4096 --output vbmeta_disabled.img

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: A23-Fragmenter-Kernel
          path: |
            kernel_source/arch/arm64/boot/Image
            vbmeta_disabled.img
